name: Cron

on:
  schedule:
    - cron:  '0 */10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: git Actions
      uses: srt32/git-actions@v0.0.3
    
    - name: add a commit for build trigger periodically
      run: |
        touch .trigger
        now=$(date "+%Y-%m-%dT%H:%M:%S%z")
        echo Git Action Time: $now >> .trigger
        git commit -m"build trigger: $now"
        git push origin master
