name: CI

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: git actions
      uses: srt32/git-actions@v0.0.3
    
    - name: add a commit for build trigger periodically
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "Git Bot"
        now=$(date "+%Y-%m-%dT%H:%M:%S%z")
        touch .trigger
        echo Git Action Time: $now >> .trigger
        git add .trigger
        git commit -m"build trigger: $now"
        git push origin master
